import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import SmoothScroll from "@/SmoothScroll";
import CursorEffect from "@/CursorEffects";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zahidul Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col dark:bg-(--bg-dark) bg-(--bg-light) ">
        <SmoothScroll />
        <div className="cursor" id="cursor"></div>
        <div className="cursor-follower" id="follower"></div>
        <CursorEffect />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
